# Package Overview
package_name: titanic_survived_prediction

# Data Files
training_data_file: train_data.csv
test_data_file: test_data.csv

# the name of pipeline and pipeline we will save after training
pipeline_name: classification_model
data_preparation_pipeline_save_file: data_preparation_output_v
feature_engineering_pipeline_save_file: feature_engineering_output_v
classification_model_pipeline_save_file: classification_model_output_v
data_preparation_pipeline_dir: data_preparation_pipeline
features_engineering_pipeline_dir: features_engineering_pipeline
training_estimator_pipeline_dir: training_estimator_pipeline

# Variables
# The variable we are attempting to predict (sale price)
target: survived

# all feature (list) in the initial training data set after data preparation step
features_after_dp:
  - pclass
  - sex
  - age
  - sibsp
  - parch
  - fare
  - cabin
  - embarked
  - title

# all feature (list) in the initial data set
initial_features:
  - pclass
  - name
  - sex
  - age
  - sibsp
  - parch
  - ticket
  - fare
  - cabin
  - embarked
  - boat
  - body
  - homedest

  # all variables (list) in the initial training data set
initial_variables:
  - pclass
  - survived
  - name
  - sex
  - age
  - sibsp
  - parch
  - ticket
  - fare
  - cabin
  - embarked
  - boat
  - body
  - homedest

# all feature (list) will use to train pipeline and predict
train_features:
  - pclass
  - age
  - sibsp
  - parch
  - fare
  - age_na
  - fare_na
  - age_outliers
  - sibsp_outliers
  - parch_outliers
  - fare_outliers
  - sex_female
  - cabin_Rare
  - cabin_Missing
  - cabin_B
  - embarked_S
  - embarked_Q
  - title_Mrs
  - title_Miss
  - title_Mr

# all feature (list) selected after feature selection performed
# selected_features:
#  -
#  -

# set test size in splitting / and therefore train size also
test_size: 0.2

# to set the random seed
random_state: 0

C: 0.0005

# number of split for KFold
n_lots: 5

# missing value to search in data set and replace by na
search_missing_value_list:
  - N/A
  - na
  - NaN
  - none
  - null
  - n/a
  - NA
  - n/a
  - n.a.
  - undefined
  - unknown
  - missing
  - '?'
  - '...'
  - '-'

# CATEGORICAL VARIABLES
# categorical variables to casted
categorical_variables_first_split:
  - cabin

# categorical variables to extract Mr, Miss, ...
categorical_variables_extract_title:
  - name

# all variables
categorical_variables:
  - sex
  - cabin
  - embarked
  - title

# with NAN missing
categorical_variables_with_na_missing:
  - cabin

# with NAN frequent
categorical_variables_with_na_frequent:
  - embarked

# others categorical variables (categorical variable -quality variables)
others_variables:
  - sex
  - cabin
  - embarked
  - title

# rare categorical variables
rare_variables:
  - cabin
  - title

# drop variables
drop_variables:
  - name
  - ticket
  - boat
  - body
  - homedest

# NUMERICAL VARIABLES
# numerical variable to cast
numerical_variables_casted:
  - fare
  - age

# all numerical variables
numerical_variables:
  - pclass
  - age
  - sibsp
  - parch
  - fare

# with NAN
numerical_variables_with_na:
  - age
  - fare

# temporal variables
# temporal_variables:
#  -

# discrete variables
discrete_variables:
  - pclass
  - sibsp
  - parch

# continuous variables
continuous_variables:
  - age
  - fare

# variables to quantile transform
numerical_quantile_variables:
  - pclass
  - age
  - fare

# binarize variables
binarize_variables:
  - sibsp
  - parch

# outliers variables
outliers_variables:
  - age
  - sibsp
  - parch
  - fare